// <auto-generated />
using System;
using Inferno.src.Adapters.Outbound.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inferno.Migrations
{
    [DbContext(typeof(HellDbContext))]
    [Migration("20251231034919_FreshStart")]
    partial class FreshStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Cavern", b =>
                {
                    b.Property<Guid>("IdCavern")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCavern");

                    b.ToTable("Caverns");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Demon", b =>
                {
                    b.Property<Guid>("IdDemon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDemon");

                    b.HasIndex("CategoryId");

                    b.ToTable("Demons");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Hell", b =>
                {
                    b.Property<Guid>("IdHell")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdHell");

                    b.ToTable("Hell");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Persecution", b =>
                {
                    b.Property<Guid>("IdDemon")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdSoul")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDemon", "IdSoul");

                    b.HasIndex("IdSoul");

                    b.ToTable("Persecution");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Realize", b =>
                {
                    b.Property<Guid>("IdSin")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdSoul")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSin", "IdSoul");

                    b.HasIndex("IdSoul");

                    b.ToTable("Realize");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Sin", b =>
                {
                    b.Property<Guid>("IdSin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdSoul")
                        .HasColumnType("TEXT");

                    b.Property<string>("SinName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SinSeverity")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdSin");

                    b.HasIndex("IdSoul");

                    b.ToTable("Sins");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Soul", b =>
                {
                    b.Property<Guid>("IdSoul")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CavernId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdSoul");

                    b.HasIndex("CavernId");

                    b.ToTable("Souls");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Demon", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Category", "Category")
                        .WithMany("Demons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Persecution", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Demon", "Demon")
                        .WithMany("Persecutions")
                        .HasForeignKey("IdDemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inferno.src.Core.Domain.Entities.Soul", "Soul")
                        .WithMany("Persecutions")
                        .HasForeignKey("IdSoul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demon");

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Realize", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Sin", "Sin")
                        .WithMany("Realizes")
                        .HasForeignKey("IdSin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inferno.src.Core.Domain.Entities.Soul", "Soul")
                        .WithMany("Realizes")
                        .HasForeignKey("IdSoul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sin");

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Sin", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Soul", "Soul")
                        .WithMany("Sins")
                        .HasForeignKey("IdSoul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Soul", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Cavern", "Cavern")
                        .WithMany("Souls")
                        .HasForeignKey("CavernId");

                    b.Navigation("Cavern");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Demons");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Cavern", b =>
                {
                    b.Navigation("Souls");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Demon", b =>
                {
                    b.Navigation("Persecutions");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Sin", b =>
                {
                    b.Navigation("Realizes");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Soul", b =>
                {
                    b.Navigation("Persecutions");

                    b.Navigation("Realizes");

                    b.Navigation("Sins");
                });
#pragma warning restore 612, 618
        }
    }
}
