// <auto-generated />
using System;
using Inferno.src.Adapters.Outbound.Persistence.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inferno.Migrations
{
    [DbContext(typeof(HellDbContext))]
    [Migration("20260315225959_ConfigJWT")]
    partial class ConfigJWT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IdCategory");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CategoryName");

                    b.HasKey("IdCategory");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Cavern", b =>
                {
                    b.Property<Guid>("IdCavern")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CavernName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCavern");

                    b.ToTable("Caverns");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Demon", b =>
                {
                    b.Property<Guid>("IdDemon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IdDemon");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DemonEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemonName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DemonName");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("IdDemon");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Demon", (string)null);
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Hell", b =>
                {
                    b.Property<Guid>("IdHell")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HellName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHell");

                    b.ToTable("Hell");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.HellTask", b =>
                {
                    b.Property<Guid>("HellTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DemonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("HellTaskId");

                    b.HasIndex("DemonId");

                    b.ToTable("HellTasks");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Image", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("IdImage");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Persecution", b =>
                {
                    b.Property<Guid>("IdDemon")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdSoul")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDemon", "IdSoul");

                    b.HasIndex("IdSoul");

                    b.ToTable("Persecution");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Realize", b =>
                {
                    b.Property<Guid>("IdSin")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdSoul")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSin", "IdSoul");

                    b.HasIndex("IdSoul");

                    b.ToTable("Realize");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.OutBoxEvent", b =>
                {
                    b.Property<Guid>("OutBoxEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("OutBoxEventId");

                    b.ToTable("OutBoxEvent");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Sin", b =>
                {
                    b.Property<Guid>("IdSin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdSoul")
                        .HasColumnType("TEXT");

                    b.Property<string>("SinName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SinSeverity")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdSin");

                    b.HasIndex("IdSoul");

                    b.ToTable("Sins");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Soul", b =>
                {
                    b.Property<Guid>("IdSoul")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CavernId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoulName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdSoul");

                    b.HasIndex("CavernId");

                    b.ToTable("Souls");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientURL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "Client1",
                            ClientURL = "https://client1.com",
                            Name = "Client Application 1"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "Client2",
                            ClientURL = "https://client2.com",
                            Name = "Client Application 2"
                        });
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Models.DemonRole", b =>
                {
                    b.Property<Guid>("DemonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DemonId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DemonRoles");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Admin Role",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Editor Role",
                            Name = "Editor"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Demon Role",
                            Name = "Demon"
                        });
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Models.SigninKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SigninKeys");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Demon", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Category", "Category")
                        .WithMany("Demons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inferno.src.Core.Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.HellTask", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Demon", "Demon")
                        .WithMany("HellTasks")
                        .HasForeignKey("DemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demon");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Persecution", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Demon", "Demon")
                        .WithMany("Persecutions")
                        .HasForeignKey("IdDemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inferno.src.Core.Domain.Entities.Soul", "Soul")
                        .WithMany("Persecutions")
                        .HasForeignKey("IdSoul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demon");

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.ManyToMany.Realize", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Sin", "Sin")
                        .WithMany("Realizes")
                        .HasForeignKey("IdSin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inferno.src.Core.Domain.Entities.Soul", "Soul")
                        .WithMany("Realizes")
                        .HasForeignKey("IdSoul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sin");

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Sin", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Soul", "Soul")
                        .WithMany("Sins")
                        .HasForeignKey("IdSoul")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Soul");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Soul", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Cavern", "Cavern")
                        .WithMany("Souls")
                        .HasForeignKey("CavernId");

                    b.Navigation("Cavern");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Models.DemonRole", b =>
                {
                    b.HasOne("Inferno.src.Core.Domain.Entities.Demon", "Demon")
                        .WithMany("DemonRoles")
                        .HasForeignKey("DemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inferno.src.Core.Domain.Models.Role", "Role")
                        .WithMany("DemonRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demon");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Demons");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Cavern", b =>
                {
                    b.Navigation("Souls");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Demon", b =>
                {
                    b.Navigation("DemonRoles");

                    b.Navigation("HellTasks");

                    b.Navigation("Persecutions");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Sin", b =>
                {
                    b.Navigation("Realizes");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Entities.Soul", b =>
                {
                    b.Navigation("Persecutions");

                    b.Navigation("Realizes");

                    b.Navigation("Sins");
                });

            modelBuilder.Entity("Inferno.src.Core.Domain.Models.Role", b =>
                {
                    b.Navigation("DemonRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
